name: documentation
on: [push, workflow_dispatch]

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
          - name: Get CMake
            uses: symbitic/install-cmake@master
          - name: Install Qt
            uses: jurplel/install-qt-action@v3
            with:
                install-deps: true
                cache: true
          - name: Generate CMake env
            shell: bash
            run: |
              cmake -DBUILD_DOCS=ON -DBUILD_EXAMPLES=OFF ..
              make doc-witmotion-uart-qt

